# Generated by Django 2.0.6 on 2018-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='first_name',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_name',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='referrer',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
